packages:
  - apps/*
  - packages/*

allowBuilds:
  "@opensea/seaport-js": false
  bufferutil: true
  keccak: true
  unrs-resolver: true
  utf-8-validate: true

peerDependencyRules:
  allowedVersions:
    "use-sync-external-store>react": "19"
