/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/healthz": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["getHealth"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/config": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["getConfig"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/assets": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["listAssets"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/assets/{slug}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["getAsset"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/nfts": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description Runtime Hoodi mint catalog projected from canonical chain events. */
    get: operations["listMintedNFTs"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/projects": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["listProjects"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/portfolio/{address}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["getPortfolio"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/indexer/events": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["ingestChainEvent"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/indexer/market-events": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** @description Credential-gated ingestion for normalized, read-only events from approved marketplaces. */
    post: operations["ingestExternalMarketEvent"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/indexer/market-snapshots": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** @description Atomically commits a complete NDJSON marketplace snapshot; any invalid or interrupted line rolls back the whole snapshot, while an empty body records a valid zero-event cutover. */
    post: operations["ingestExternalMarketSnapshot"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/market/activity": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description Read-only activity mirrored from approved external marketplaces; execution remains external. */
    get: operations["getExternalMarketActivity"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/market/assets": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description Paginated, deduplicated NFT catalog derived only from attributed external-market runtime events. */
    get: operations["getExternalMarketAssets"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/market/intents": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** @description Build an unsigned, same-chain OpenSea fulfillment plan. The external wallet and OpenSea/Seaport retain signing and execution. */
    post: operations["createExternalMarketIntent"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/market/intents/{intentID}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["getExternalMarketIntent"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/market/intents/{intentID}/submission": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["recordExternalMarketSubmission"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/governance/config": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description Hoodi RWA DAO addresses and immutable policy thresholds. Disabled unless every address is valid. */
    get: operations["getGovernanceConfig"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/governance/proposals": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description Durable chain-indexed governance proposals. No fixture fallback is permitted. */
    get: operations["getGovernanceProposals"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/uploads/intents": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["createUploadIntent"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/uploads/{uploadID}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put: operations["uploadObject"];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/rwa/intents": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["createMintIntent"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/rwa/intents/{intentID}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["getMintIntent"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/rwa/intents/{intentID}/submission": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["recordMintSubmission"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/rwa/discovery-checks": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** @description Operator-authenticated, server-side OpenSea NFT discovery check. The API key and raw upstream payload remain private; the result and payload digest are recorded durably. */
    post: operations["checkOpenSeaDiscovery"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/vault/intents": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["createVaultIntent"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/vault/intents/{intentID}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["getVaultIntent"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/vault/intents/{intentID}/submission": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["recordVaultSubmission"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    Status: {
      service: string;
      status: string;
      version: string;
    };
    Config: {
      /** @constant */
      api: "v1";
      /** @constant */
      chainId: 560048;
      /** @constant */
      mode: "preview";
      /** @constant */
      network: "hoodi";
      readOnly: boolean;
      writeEnabled: boolean;
      registryAddress?: string;
      vaultFactoryAddress?: string;
    };
    GovernanceConfig: {
      actionRegistryAddress?: string;
      approvalPpm: {
        /** @constant */
        marketMigration: 500000;
        /** @constant */
        physicalAction: 666667;
        /** @constant */
        forcedBuyout: 800000;
      };
      /** @constant */
      chainId: 560048;
      enabled: boolean;
      governorAddress?: string;
      /** @constant */
      membershipAuthority: "onchain-rwa-token-snapshot";
      /** @constant */
      proposalThresholdPpm: 100000;
      tokenAddress?: string;
      vaultAddress?: string;
    };
    GovernanceProposal: {
      actionTarget: string;
      /** @enum {integer} */
      approvalNumerator: 500000 | 666667 | 800000;
      /** @constant */
      approvalDenominator: 1000000;
      evidenceHash?: string;
      /** Format: uri */
      evidenceUri?: string;
      governorAddress: string;
      proposalId: string;
      /** @enum {string} */
      proposalKind: "market_migration" | "physical_action" | "forced_buyout";
      proposerAddress: string;
      rwaVerified: boolean;
      /** @enum {string} */
      status:
        | "pending"
        | "active"
        | "defeated"
        | "succeeded"
        | "queued"
        | "executed"
        | "cancelled";
      voteStart: number;
      voteEnd: number;
    };
    UploadIntentRequest: {
      fileName: string;
      /** @enum {string} */
      contentType: "image/png" | "image/jpeg" | "image/webp";
      sha256: string;
      size: number;
    };
    UploadIntent: {
      uploadId: string;
      uploadUrl: string;
      /** @constant */
      method: "PUT";
      /** Format: date-time */
      expiresAt: string;
      /** @constant */
      maxBytes: 10485760;
      requiredHeaders: {
        [key: string]: string;
      };
    };
    MintIntentRequest: {
      uploadId: string;
      recipient: string;
      name: string;
      artist: string;
      year: number;
      medium: string;
      location: string;
      description: string;
    };
    MintIntent: {
      intentId: string;
      requestId: string;
      recipient: string;
      registryAddress: string;
      /** @constant */
      chainId: 560048;
      /** Format: uri */
      metadataUri: string;
      metadataSha256: string;
      /** @constant */
      contractFunction: "createAsset(bytes32,address,string,bytes32)";
      contractArguments: string[];
      /** @enum {string} */
      status: "prepared" | "submitted" | "confirmed" | "failed";
      transactionHash?: string;
      /** Format: date-time */
      createdAt: string;
    };
    OpenSeaDiscoveryRequest: {
      /** @constant */
      source: "opensea";
      chain: string;
      contractAddress: string;
      tokenId: string;
    };
    OpenSeaDiscoveryResult: {
      checkId: string;
      /** @constant */
      source: "opensea";
      chain: string;
      contractAddress: string;
      tokenId: string;
      /** @enum {string} */
      result: "discovered" | "not-found" | "unsupported-chain";
      discovered: boolean;
      collection?: string;
      tokenStandard?: string;
      /** Format: uri */
      marketplaceUrl?: string;
      evidenceSha256: string;
      upstreamStatus: number;
      /** Format: date-time */
      observedAt: string;
    };
    VaultIntentRequest: {
      collectionAddress: string;
      tokenId: string;
      vaultName: string;
      adminAddress: string;
      pauserAddress: string;
      fractionalizerAddress: string;
    };
    VaultIntent: {
      intentId: string;
      requestId: string;
      factoryAddress: string;
      collectionAddress: string;
      tokenId: string;
      vaultName: string;
      adminAddress: string;
      pauserAddress: string;
      fractionalizerAddress: string;
      /** @constant */
      chainId: 560048;
      /** @constant */
      contractFunction: "createVault(bytes32,string,address,uint256,address,address,address)";
      contractArguments: string[];
      /** @enum {string} */
      status:
        | "prepared"
        | "submitted"
        | "created"
        | "deposited"
        | "fractionalized"
        | "failed";
      transactionHash?: string;
      /** Format: date-time */
      createdAt: string;
    };
    Asset: {
      slug: string;
      title: string;
      artist: string;
      year: number;
      medium: string;
      location: string;
      valuationUsd: number;
      fractionPriceUsd: number;
      totalFractions: number;
      availableFractions: number;
      status: string;
      provenance: string[];
    };
    MintedNFT: {
      /** @enum {string} */
      standard: "ERC-721" | "ERC-1155";
      collectionAddress: string;
      tokenId: string;
      holderAddress?: string;
      /** Format: uri */
      metadataUri?: string;
      transactionHash: string;
      blockNumber: number;
      /** Format: date-time */
      observedAt: string;
    };
    Project: {
      slug: string;
      name: string;
      curator: string;
      location: string;
      assetSlugs: string[];
      description: string;
    };
    Portfolio: {
      address: string;
      /** @constant */
      chainId: 560048;
      /** @constant */
      network: "hoodi";
      positions: {
        assetToken: string;
        symbol: string;
        balance: string;
        /** Format: date-time */
        updatedAt: string;
      }[];
      transactions: Record<string, never>[];
      offers: Record<string, never>[];
      notifications: Record<string, never>[];
    };
    ChainEventRequest: {
      /** @constant */
      chainId: 560048;
      transactionHash: string;
      logIndex: number;
      blockNumber: number;
      blockHash: string;
      contractAddress: string;
      eventName: string;
      payload: Record<string, never>;
      removed: boolean;
      confirmations: number;
    };
    ExternalMarketEventRequest: {
      /** @constant */
      schemaVersion: "1";
      source: string;
      eventType: string;
      /** @enum {string} */
      eventFamily: "order" | "sale" | "transfer" | "metadata";
      entityKey: string;
      version: number;
      chain: string;
      collectionSlug?: string;
      orderHash?: string;
      transactionHash?: string;
      contractAddress?: string;
      tokenId?: string;
      makerAddress?: string;
      price?: string;
      paymentTokenAddress?: string;
      paymentSymbol?: string;
      /** Format: uri */
      marketplaceUrl?: string;
      /** Format: date-time */
      eventTimestamp: string;
      payload: Record<string, never>;
    };
    ExternalMarketActivity: components["schemas"]["ExternalMarketEventRequest"] & {
      eventId: string;
    };
    ExternalMarketAsset: {
      source: string;
      chain: string;
      contractAddress: string;
      tokenId: string;
      collectionSlug?: string;
      latestEventType: string;
      /** Format: date-time */
      latestEventTimestamp: string;
      orderHash?: string;
      /** @enum {string} */
      orderStatus?: "active" | "cancelled" | "invalidated" | "fulfilled";
      price?: string;
      paymentSymbol?: string;
      /** Format: uri */
      marketplaceUrl?: string;
    };
    ExternalMarketIntentRequest: {
      /** @constant */
      source: "opensea";
      /** @constant */
      action: "fulfill-listing";
      chain: string;
      orderHash: string;
      walletAddress: string;
    };
    ExternalMarketTransaction: {
      chain: string;
      to: string;
      data: string;
      value: string;
      valueHex?: string;
    };
    ExternalMarketIntent: components["schemas"]["ExternalMarketIntentRequest"] & {
      intentId: string;
      contractAddress: string;
      tokenId: string;
      /** @enum {string} */
      status:
        | "initiated"
        | "awaiting-wallet"
        | "submitted"
        | "accepted"
        | "rejected"
        | "pending"
        | "confirmed"
        | "failed"
        | "cancelled";
      /** Format: uri */
      marketplaceUrl: string;
      transactions: components["schemas"]["ExternalMarketTransaction"][];
      transactionHash?: string;
      externalTransactionHash?: string;
      failureCode?: string;
      /** Format: date-time */
      externalEventTimestamp?: string;
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      updatedAt: string;
    };
    Problem: {
      /** Format: uri */
      type: string;
      title: string;
      status: number;
      detail: string;
      requestId: string;
    };
  };
  responses: {
    /** @description RFC 9457-style request failure */
    Problem: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/problem+json": components["schemas"]["Problem"];
      };
    };
  };
  parameters: {
    IntentID: string;
  };
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  getHealth: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Service health */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Status"];
        };
      };
    };
  };
  getConfig: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Safe public runtime configuration */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Config"];
        };
      };
    };
  };
  listAssets: {
    parameters: {
      query?: {
        q?: string;
        status?: string;
        page?: number;
        pageSize?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Asset catalog */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            data: components["schemas"]["Asset"][];
            total: number;
            page: number;
            pageSize: number;
          };
        };
      };
    };
  };
  getAsset: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        slug: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Asset record */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Asset"];
        };
      };
      404: components["responses"]["Problem"];
    };
  };
  listMintedNFTs: {
    parameters: {
      query?: {
        page?: number;
        pageSize?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Indexed ERC-721 and ERC-1155 mint records */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            data: components["schemas"]["MintedNFT"][];
            total: number;
            page: number;
            pageSize: number;
            /** @constant */
            chainId: 560048;
            /** @constant */
            runtime: true;
          };
        };
      };
    };
  };
  listProjects: {
    parameters: {
      query?: {
        q?: string;
        page?: number;
        pageSize?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Curated projects */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            data: components["schemas"]["Project"][];
            total: number;
            page: number;
            pageSize: number;
          };
        };
      };
    };
  };
  getPortfolio: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        address: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Read-only public address portfolio */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Portfolio"];
        };
      };
      400: components["responses"]["Problem"];
    };
  };
  ingestChainEvent: {
    parameters: {
      query?: never;
      header: {
        "X-Indexer-Key": string;
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ChainEventRequest"];
      };
    };
    responses: {
      /** @description Replay */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Canonical event created */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      401: components["responses"]["Problem"];
      409: components["responses"]["Problem"];
    };
  };
  ingestExternalMarketEvent: {
    parameters: {
      query?: never;
      header: {
        "X-Indexer-Key": string;
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ExternalMarketEventRequest"];
      };
    };
    responses: {
      /** @description Idempotent replay accepted */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description External marketplace event mirrored */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      401: components["responses"]["Problem"];
      422: components["responses"]["Problem"];
    };
  };
  ingestExternalMarketSnapshot: {
    parameters: {
      query?: never;
      header: {
        "X-Indexer-Key": string;
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/x-ndjson": string;
      };
    };
    responses: {
      /** @description Complete external marketplace snapshot committed atomically */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      400: components["responses"]["Problem"];
      401: components["responses"]["Problem"];
      413: components["responses"]["Problem"];
      415: components["responses"]["Problem"];
      422: components["responses"]["Problem"];
    };
  };
  getExternalMarketActivity: {
    parameters: {
      query?: {
        source?: string;
        contract?: string;
        limit?: number;
        /** @description Opaque position from a previous response's nextCursor. Keyset, not an offset: a feed that grows at its head would make offset paging skip and repeat rows. A cursor this endpoint did not issue is refused rather than rounded to the start. */
        cursor?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Attributed external marketplace activity */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            data: components["schemas"]["ExternalMarketActivity"][];
            /** @constant */
            schemaVersion: "1";
            source: string;
            /** @constant */
            execution: "external-deeplink-only";
            /** @constant */
            custody: false;
            /** @description Position to pass as cursor for the next page. Absent once the history has ended, so its absence is the end rather than something to infer from a short page. */
            nextCursor?: string;
          };
        };
      };
      400: components["responses"]["Problem"];
      503: components["responses"]["Problem"];
    };
  };
  getExternalMarketAssets: {
    parameters: {
      query?: {
        source?: string;
        contract?: string;
        page?: number;
        pageSize?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Complete runtime-backed page of mirrored NFTs */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            data: components["schemas"]["ExternalMarketAsset"][];
            total: number;
            page: number;
            pageSize: number;
            /** @constant */
            schemaVersion: "1";
            source: string;
            /** @constant */
            runtime: true;
          };
        };
      };
      400: components["responses"]["Problem"];
      503: components["responses"]["Problem"];
    };
  };
  createExternalMarketIntent: {
    parameters: {
      query?: never;
      header: {
        "Idempotency-Key": string;
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ExternalMarketIntentRequest"];
      };
    };
    responses: {
      /** @description Idempotent replay */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ExternalMarketIntent"];
        };
      };
      /** @description Safe unsigned transaction plan prepared for external-wallet review */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ExternalMarketIntent"];
        };
      };
      409: components["responses"]["Problem"];
      422: components["responses"]["Problem"];
      503: components["responses"]["Problem"];
    };
  };
  getExternalMarketIntent: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        intentID: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Current state reconciled from wallet submission and external-market events */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ExternalMarketIntent"];
        };
      };
      404: components["responses"]["Problem"];
    };
  };
  recordExternalMarketSubmission: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        intentID: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": {
          transactionHash: string;
        };
      };
    };
    responses: {
      /** @description External-wallet submission recorded for authoritative event reconciliation */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ExternalMarketIntent"];
        };
      };
      409: components["responses"]["Problem"];
    };
  };
  getGovernanceConfig: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Governance deployment configuration */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["GovernanceConfig"];
        };
      };
    };
  };
  getGovernanceProposals: {
    parameters: {
      query?: {
        limit?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Indexed governance proposal records */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            data: components["schemas"]["GovernanceProposal"][];
            /** @constant */
            membershipAuthority: "onchain-rwa-token-snapshot";
            /** @constant */
            schemaVersion: "1";
          };
        };
      };
      503: components["responses"]["Problem"];
    };
  };
  createUploadIntent: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UploadIntentRequest"];
      };
    };
    responses: {
      /** @description Short-lived digest-bound API upload intent */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["UploadIntent"];
        };
      };
      422: components["responses"]["Problem"];
      503: components["responses"]["Problem"];
    };
  };
  uploadObject: {
    parameters: {
      query?: never;
      header: {
        "Content-SHA256": string;
      };
      path: {
        uploadID: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "image/png": string;
        "image/jpeg": string;
        "image/webp": string;
      };
    };
    responses: {
      /** @description Object digest verified and persisted */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      400: components["responses"]["Problem"];
      422: components["responses"]["Problem"];
    };
  };
  createMintIntent: {
    parameters: {
      query?: never;
      header: {
        "Idempotency-Key": string;
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["MintIntentRequest"];
      };
    };
    responses: {
      /** @description Idempotent replay of an existing intent */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["MintIntent"];
        };
      };
      /** @description New immutable metadata and contract-call intent */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["MintIntent"];
        };
      };
      409: components["responses"]["Problem"];
      422: components["responses"]["Problem"];
    };
  };
  getMintIntent: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        intentID: components["parameters"]["IntentID"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Mint transaction lifecycle snapshot */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["MintIntent"];
        };
      };
      404: components["responses"]["Problem"];
    };
  };
  recordMintSubmission: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        intentID: components["parameters"]["IntentID"];
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": {
          transactionHash: string;
        };
      };
    };
    responses: {
      /** @description Submitted transaction attached idempotently */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["MintIntent"];
        };
      };
      409: components["responses"]["Problem"];
    };
  };
  checkOpenSeaDiscovery: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["OpenSeaDiscoveryRequest"];
      };
    };
    responses: {
      /** @description Discovery evidence recorded, including explicit not-found or unsupported-chain outcomes */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["OpenSeaDiscoveryResult"];
        };
      };
      401: components["responses"]["Problem"];
      422: components["responses"]["Problem"];
      502: components["responses"]["Problem"];
      503: components["responses"]["Problem"];
    };
  };
  createVaultIntent: {
    parameters: {
      query?: never;
      header: {
        "Idempotency-Key": string;
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["VaultIntentRequest"];
      };
    };
    responses: {
      /** @description Idempotent replay */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["VaultIntent"];
        };
      };
      /** @description New VaultFactory transaction intent */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["VaultIntent"];
        };
      };
      409: components["responses"]["Problem"];
    };
  };
  getVaultIntent: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        intentID: components["parameters"]["IntentID"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Vault transaction lifecycle snapshot */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["VaultIntent"];
        };
      };
      404: components["responses"]["Problem"];
    };
  };
  recordVaultSubmission: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        intentID: components["parameters"]["IntentID"];
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": {
          transactionHash: string;
        };
      };
    };
    responses: {
      /** @description Submitted VaultFactory transaction attached idempotently */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["VaultIntent"];
        };
      };
    };
  };
}
